### ISSUE TITLE
over-active github wdl syntax highlighting 

### ISSUE THREAD

**Issue by ambrosejcarr** [broadinstitute/wdl-sublime-syntax-highlighter#4]
It seems like the wdl syntax highlighting on Github is a bit off. See, e.g. https://github.com/HumanCellAtlas/skylab/pull/51/files

where keywords such as  `input`, `if`, etc are getting highlighted everywhere, as opposed to only being highlighted when used as keywords.

**Comment by rexwangcc** [comment]
@ambrosejcarr I don't know syntax highlighting too much, but it seems there's something need to be done with https://github.com/github/linguist/blob/f75c5707a62a3d66501993116826f4e64c3ca4dd/lib/linguist/languages.yml#L1

**Comment by dannykwells** [comment]
This is a general issue in Sublime too - I think due to this line: 
"
 keywords:
    patterns:
    - name: keyword.other.wdl
      match: \s*(call|command|output|runtime|task|workflow|

"
We'll update if we make any progress. It seems like there is good syntax highlighting on FireCloud - perhaps that could be used here?

**Comment by cjllanwarne** [comment]
@rexwangcc linguist is already set up to point at this repo, so they'll pick up any updates we make here automatically

@dannykwells if FC uses a sublime markup for their highlighting and it's better than ours, absolutely we can see about swapping them out.

**Comment by cjllanwarne** [comment]
Fix under review in #5
